name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-debug:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t local-debug-image .

    - name: Run Docker container
      run: |
        docker run --name app-container -d --rm -v ${{ github.workspace }}:/app -p 12345:12345 local-debug-image
        sleep 10  # Allow time for the container to start and potentially hit a breakpoint

    - name: Check for debugging session
      run: |
        if docker exec app-container pgrep -f "python ./debug.py"; then
          echo "Debugger has been activated due to an error."
          # Here you would need to adapt how to fetch logs from your application
          # This assumes you have set up a mechanism to retrieve logs
        else
          echo "No debugging session detected."
        fi

    - name: Upload debugging logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: debugging-logs
        path: ./debugging-logs.txt
