name: Python Application Debugging

on: [push]

jobs:
  build-and-debug:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Checkout the repository

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python-debug  # Build Docker image

    - name: Run Docker container with debugging
      run: |
        # Run the Docker container without TTY
        docker run --rm \
          --name python-debug-container \
          -v ${{ github.workspace }}/debug.log:/app/debug.log \
          python-debug  # Run the container

    - name: Upload debugging log
      uses: actions/upload-artifact@v2  # Upload the debug logs
      with:
        name: debug-logs
        path: debug.log  # Path to the log file to be uploaded
