# .github/workflows/debug-pipeline.yml
name: Automated Debugging Pipeline

on: [push, pull_request]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t python-debug .

      - name: Run Docker container and capture logs
        run: |
          docker run --name python-debug-container -d python-debug
          docker logs python-debug-container > debug_logs.txt

      - name: Store debugging logs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: debug-logs
          path: debug_logs.txt
