name: Continuous Integration

on: [push, pull_request]

jobs:
  build-and-debug:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t local-debug-image .  # Build the image locally

    - name: Run Docker container
      run: |
        docker run --name app-container -d --rm -v ${PWD}:/app -p 12345:12345 local-debug-image  # Use the local image
        sleep 10 # Give it some time to start up and potentially hit a breakpoint

    - name: Check for debugging session
      run: |
        if docker exec app-container pgrep -f "python ./debug.py"; then
          echo "Debugger has been activated due to an error."
          docker exec app-container curl http://localhost:12345/debugger-logs
        else
          echo "No debugging session detected."
        fi

    - name: Upload debugging logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: debugging-logs
        path: ./debugging-logs.txt
