# .github/workflows/terraform.yml
name: Terraform Apply

on: [push]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply with Logging
      run: terraform apply -auto-approve | tee terraform-apply.log
      if: ${{ success() }}

    - name: Upload Terraform Logs
      uses: actions/upload-artifact@v2
      with:
        name: terraform-apply-logs
        path: terraform-apply.log
      if: ${{ always() }}
