# .github/workflows/deploy.yml
name: Deploy Application

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Terraform
      run: # Terraform setup commands

    - name: Terraform Apply
      run: |
        set +e
        terraform apply -auto-approve
        exit_code=$?
        set -e
        if [ $exit_code -ne 0 ]; then
          echo "Terraform apply failed"
          exit $exit_code
        fi
