name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**.tf'

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: 'Terraform'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: cd terraform && terraform init

    - name: Terraform Plan
      run: cd terraform && terraform plan

    - name: Terraform Apply
      run: cd terraform && terraform apply -auto-approve
