# .github/workflows/deploy.yml
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: |
        if terraform apply -auto-approve; then
          echo "Terraform apply succeeded"
        else
          echo "Terraform apply failed" >&2
          exit 1
        fi

    - name: Deploy Application
      run: # Deployment command
      if: success() # Only run if previous steps were successful
