# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply (Test Environment)
      run: terraform apply -auto-approve -var 'environment=test'

    - name: Deploy Application (Test Environment)
      run: # Your deployment command

    - name: Run Tests
      run: # Your test command

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply (Production Environment)
      run: terraform apply -auto-approve -var 'environment=production'

    - name: Deploy Application (Production Environment)
      run: # Your deployment command

    - name: Production Health Checks
      run: # Your health check command
