# .github/workflows/deploy.yml
name: Deploy Python Application

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Tests
      run: pytest

    - name: Deploy Application
      run: |
        try:
          # Your deployment script/command
        except Exception as e:
          print(f"Deployment failed with error: {e}")
          # Log error and exit with non-zero status
          exit(1)
