name: Python application CI

on: [push, pull_request]

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run Pylint
      run: |
        pylint --rcfile=.pylintrc main.py
      continue-on-error: true # This allows the pipeline to continue even if Pylint fails, for reporting purposes.
    - name: Upload Pylint report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: pylint-report
        path: pylint_report.txt
