stages:
  - test
  - security_scan

bandit-security-scan:
  stage: security_scan
  image: python:3.8
  script:
    - pip install bandit
    - bandit -r src -x src/tests -o bandit-report.txt -f txt
  artifacts:
    paths:
      - bandit-report.txt
  when: always
