# Name of the GitHub Actions workflow
name: 'Terraform CI/CD'

# Event triggers to run this workflow
on:
  push:  # Trigger the workflow on a push event
    branches:
      - main  # Only trigger when changes are pushed to the 'main' branch
    paths:
      - 'terraform/**.tf' 

# Define the jobs that will run within this workflow
jobs:
  terraform:
    runs-on: ubuntu-latest  # Specify the OS environment for running the job (Ubuntu)

    name: 'Terraform'  # Job name

    steps:
    # Step 1: Checkout the repository to get the code
    - name: Checkout repository
      uses: actions/checkout@v2  # Use the GitHub-provided action to check out the code from the repository

    # Step 2: Set up Terraform in the environment
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1  # Use the official Terraform GitHub Action to set up the Terraform CLI

    # Step 3: Initialize Terraform
    - name: Terraform Init
      run: cd terraform && terraform init  # Navigate to the 'terraform' directory and run 'terraform init'

    # Step 4: Run Terraform plan to preview the changes
    - name: Terraform Plan
      run: cd terraform && terraform plan  # Run 'terraform plan' to preview the infrastructure changes

    # Step 5: Apply the Terraform configuration automatically
    - name: Terraform Apply
      run: cd terraform && terraform apply -auto-approve  # Apply the changes without manual approval
