name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**/*.tf'  # Trigger for any .tf files in terraform folder

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: 'Terraform'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.3.0'

    - name: Terraform Init
      id: init
      run: terraform init terraform  # Ensure you specify the path if needed

    - name: Terraform Plan
      id: plan
      run: terraform plan terraform  # Run in the correct directory

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve terraform  # Run in the correct directory
